const QUERY_KEY = {
	GET_MAINPAGE_MAIN_DATA: 'GET_MAINPAGE_MAIN_DATA',
	GET_MYPAGE_MAIN_DATA: 'GET_MYPAGE_MAIN_DATA',
	GET_MYPAGE_BANK_LIST: 'GET_MYPAGE_BANK_LIST',
	GET_SEARCHPAGE_DATA: 'GET_SEARCHPAGE_DATA',
	GET_DETAILPAGE_DATA: 'GET_DETAILPAGE_DATA',
	GET_DETAIL_INTEREST_DATA: 'GET_DETAIL_INTEREST_DATA',
	GET_LIKED_DATA: 'GET_LIKED_DATA',

}
export default QUERY_KEY
